version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: circleci/node:8
    steps:
      - run: yarn global add exp
      - checkout
      - run: yarn
      - run: yarn test
      - persist_to_workspace:
          root: ~/project
          paths:
            - node_modules

  android:
    working_directory: ~/project
    docker:
      - image: circleci/android:api-27-node8-alpha
    steps:
      - run: exp build:android

  ios:
    macos:
      xcode: "9.0"
    steps:
      - run: exp build:ios .

  publish:
    macos:
      xcode: "9.0"
    steps:
      - run: exp publish .

workflows:
  version: 2
  node-android-ios:
    jobs:
      - build
      - android:
          requires:
            - build
      - ios:
          requires:
            - build
     - publish:
          requires:
            - android
            - ios